### PR TITLE
Windowless

### PR DESCRIPTION
**Pull request by psivasubramanian**
Windowless backend support

### CODE REVIEW

**Comment by kraj** [comment]
The commit messages need to improve. Please add a short description of the given commit and not a general sweeping statement like it seems to be right now for every commit.

**Comment by psivasubramanian** [comment]
Not sure on whether to edit existing commits or make new ones. Tried to add to existing ones, but it's showing as comment on the commit.

**Comment by psivasubramanian** [comment]
created https://github.com/Metrological/WebKitForWayland/pull/40 with better commit messages

**Comment by philn** [comment]
You could also git  push -f of the branch and this PR would've been updated.

**Pull request closed without merging**
