### PR TITLE
Don't drop privilege as making libgcrypt calls

### PR DESCRIPTION
**Pull request by MingyenHung**
Change source branch to subject branch: wpe-20170728-dont-drop-privilege
For more detail and comments, please refer to previous PR(#491).

### CODE REVIEW

**Comment by charlie-ht** [comment]
Is this still an issue for you @MingyenHung ? From the PR you referenced, it seems as though there were component patches that fixed it without your PR here?

**Review by dwrobel — COMMENTED** [review]
Looks good to me. I think we need a similar fix for 2.22 as well.

**Comment by charlie-ht** [comment]
> Looks good to me. I think we need a similar fix for 2.22 as well.

Couple initial thoughts making this a non-instant merge,

  1) Why are we running webkit as root for this to be a problem?
  2) What can I do to test this fix actually does anything / works? I took a look in the libgcrypt source code, but there's no code there doing anything interesting with this flag. I literally only grepped, I know nothing about libgcrypt. The linked PR concludes with comments saying other parts of the eco-system fixed this bug.
  3) Note that upstream doesn't have this fix either, presumably because they'd find the running as root bit suspicious. If it's needed, perhaps it should be opened as a bugzilla, with a test case or at least a clear scenario outline for why it's needed.

**Comment by mcatanzaro** [comment]
> 3\. Note that upstream doesn't have this fix either, presumably because they'd find the running as root bit suspicious.

I agree that this isn't right because WebKit should never be running as root. From the commit message it's clear every process is being run with uid 0... don't do that.

**Comment by charlie-ht** [comment]
No response.

**Pull request closed without merging**
