### PR TITLE
Preload libwayland-egl library to be used for egl calls before libEGL…

### PR DESCRIPTION
**Pull request by madanagopalt**
… library for WPE westeros backend

Checked  the elf file output for wpelauncher, webprocess and networkprocess. libEGL is removed from the needed section used by loader. Also, verified strace.  Changes made in webcore, as preloading is needed by both UIProcess (to connect to main westeros compositor) and webprocess(to connect to embedded ccompositor created from UIProcess).

### CODE REVIEW

**Comment by zdobersek** [comment]
Why are these not added to WPE_PLATFORM_LIBRARIES instead?

**Comment by madanagopalt** [comment]
They are already present as part of WPE_PLATFORM_LIBRARIES. But, libWPEWebkit depends on many other other libraries say cairo, which depends on libEGL. UIProcess, webprocess and network process depends only on libWPEWebkit.so. WPEWebkit is independent of backend platform. It is linked with libEGL. So, libEGL gets loaded for every process on their startup due to WPEWebkit.so.

Later WPEPlatform.so is loaded dynamically with dlopen, based on the backend platform chosen.At that time, libEGL is loaded by WPEWebkit, so libwayland-egl has no effect.

**Comment by zdobersek** [comment]
I assume libwayland-egl exports symbols that must override the ones provided by libEGL. I'm not entirely sure listing libwayland-egl before libEGL in the CMake list ensures that libwayland-egl loads before libEGL.

I'm OK with the patch though.

**Comment by madanagopalt** [comment]
Thanks.

Yes, listing before libEGL won't work everytime in cmake. In our case, we have put it before webcore library identifies any first symbol for egl calls. I checked with the load sequence set by the static linker. Before the change, libEGL is present first in the load sequence. After change, libwayland-egl is present first in the load sequence.

**Comment by kraj** [comment]
are you trying to fix runtime load sequence by doing this ? if so it could break if the linker changes say from gold to bfd ld.

**Pull request merged**
