### PR TITLE
[wpewebkit] add EGL CFLAGS

### PR DESCRIPTION
**Pull request by moorthy-bs**
to add EGL CFLAGS from pkgconfig

yocto - 2.6 (thud)
platform - imx8mqevk (NXP's i.MX8MQ) 64bit

NXP's i.MX8MQ EGL has few defines in CFlags of egl.pc which could be used in eglplatform.h to determine Linux, wayland egl platforms. If these defines not included, causing fatal errors.
This could be a common fix so that any other platforms EGL Cflags can be included

Signed-off-by: Moorthy Baskar <moorthy.baskaravenkatraman-sambamoorthy@linaro.org>

### CODE REVIEW

**Comment by charlie-ht** [comment]
Can you adjust the commit message to include info about why you're proposing this patch. What error does it fix, on what platform / in what environment etc etc.

See also: https://bugs.webkit.org/show_bug.cgi?id=197784

**Comment by moorthy-bs** [comment]
> Can you adjust the commit message to include info about why you're proposing this patch. What error does it fix, on what platform / in what environment etc etc.
> 
> See also: https://bugs.webkit.org/show_bug.cgi?id=197784

Hi Charlie,
I've detailed the commit message

**Comment by moorthy-bs** [comment]
Hi,
I think the details given in the commit is good enough. If required more, kindly intimate.

**Comment by charlie-ht** [comment]
Hi @moorthy-bs , this looked similar to another EGL flags bug I pointed at upstream. I'll get out of the way of your review, and apologies for taking so long to see your update. If @wouterlucas and/or @zdobersek are OK with it, then great, I can't verify this patch due to no access to your reference platform.

**Comment by psivasubramanian** [comment]
Requesting @wouterlucas @zdobersek to review.
FYI @petegriffin

**Comment by moorthy-bs** [comment]
Hi @wouterlucas , @zdobersek , do you get a chance to review this?

**Review by zdobersek — APPROVED** [review]

**Pull request merged**
