### PR TITLE
Adapt speech synthesis changes from 2.28

### PR DESCRIPTION
**Pull request by Scony**
- Add missing functions
- Add proper error handling (similar to #823 with optional as in #875) for both UIProcess and WebProcess

### CODE REVIEW

**Comment by pgorszkowski-igalia** [comment]
Hi @Scony , are you able to build wpe-2.38 with ENABLE_SPEECH_SYNTHESIS=ON?

**Comment by Scony** [comment]
@pgorszkowski-igalia before/after my change there should be a compilation (linkage) error of undefined reference kind as by default there is no concrete speech synthesis implementation. If you provide some implementation (even dummy one) you will be able to build with `ENABLE_SPEECH_SYNTHESIS=ON`

**Comment by pgorszkowski-igalia** [comment]
In my case I get compilation error:
```
Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp:352:72: error: ‘WEBKIT_TYPE_FLITE_SRC’ was not declared in this scope; did you mean ‘WEBKIT_TYPE_MEDIA_SRC’?
  352 |         gst_element_register(nullptr, "webkitflitesrc", GST_RANK_NONE, WEBKIT_TYPE_FLITE_SRC);
```
I think that there are still some missing patches from upstream. I am working on fix that and that is why I was surprised that it compiles in your case.

**Comment by Scony** [comment]
@pgorszkowski-igalia that looks unrelated. Are you sure this is regression from this change of mine?

**Comment by pgorszkowski-igalia** [comment]
@Scony: yes, it is definitely unrelated to your change(sorry for misunderstanding), but before/after your change the wpe is not compilable with ENABLE_SPEECH_SYNTHESIS=ON because of that error and my concerns was how you compiled/tested it (my assumption is that you did it not on clear wpe-2.38 branch - and that is why I asked you my question).

**Comment by pgorszkowski-igalia** [comment]
PR with fix for compilation of WPE with ENABLE_SPEECH_SYNTHESIS=ON: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1055

**Comment by Scony** [comment]
> @Scony: yes, it is definitely unrelated to your change(sorry for misunderstanding), but before/after your change the wpe is not compilable with ENABLE_SPEECH_SYNTHESIS=ON because of that error and my concerns was how you compiled/tested it (my assumption is that you did it not on clear wpe-2.38 branch - and that is why I asked you my question).

ah, yes - I was compiling using `wpe-2.38` from `21 Feb`

**Pull request merged**
