### PR TITLE
Update the duration based on current and last pts of the buffer

### PR DESCRIPTION
**Pull request by kkanag314**

### CODE REVIEW

**Comment by kkanag314** [comment]
AppendPipeline has logic to derive DTS from PTS, Duration of the current & previous samples. 
The current implementation considers only the first two samples to determine the duration i.e duration = (currentPTS - lastPTS).
But If the delta between the PTS of further samples are higher than the updated sample duration, the sample duration misleads the calculation of DTS of the buffers.
This difference gets accumulated over a period and ends up in a huge difference between PTS & DTS.

The change we are proposing is to correct the duration and thus prevent DTS deviating too far from PTS. If the sample itself has valid duration / DTS this issue or logic won't be required.

We observed the issue in audio buffers of some random assets in YouTube.
The audio buffers doesn't have the valid duration and DTS.
The difference between PTS of first 2 sample is 0.0145 and Its updated as sample duration.
But the actual PTS delta between 2nd & 3rd (and upcoming) samples are 0.0200 which leads to the huge difference between PTS & DTS over time.
This huge difference in DTS is causing the issue while enqueuing the samples in provideMediaData() after the rewind.
While enqueuing the samples in trackbuffer,If the difference between the decode time of new sample and previously enqueued data sample is more than 1 second, then the new samples are not getting enqueued in the track buffer which leads to the issue.

**SourceBuffer::sourceBufferPrivateDidReceiveSample(0x9b992c00) - sample({PTS({    0/1000000 = 0.000000}), DTS({41666/1000000 = 0.041666}), duration({41666/1000000 = 0.041666}), flags(sync), trackId(A1), presentationSize(0.000000x0.000000)})
SourceBuffer::sourceBufferPrivateDidReceiveSample(0x9b992c00) - sample({PTS({14500/1000000 = 0.014500}), DTS({56166/1000000 = 0.056166}), duration({14500/1000000 = 0.014500}), flags(sync), trackId(A1), presentationSize(0.000000x0.000000)})
SourceBuffer::sourceBufferPrivateDidReceiveSample(0x9b992c00) - sample({PTS({34500/1000000 = 0.034500}), DTS({70666/1000000 = 0.070666}), duration({14500/1000000 = 0.014500}), flags(sync), trackId(A1), presentationSize(0.000000x0.000000)})**

We  have a sample app with the asset which exposes the issue. https://kkanag314.github.io/testAudio/

**Comment by kkanag314** [comment]
@eocanha Could you please review the changes

**Comment by eocanha** [comment]
This fix makes sense. Your explanation is very illustrative, so I'd like to have it as commit message. If you don't mind, I'm going to edit your commit locally, add the message myself, and commit it to wpe-2.22 on your behalf (preserving your authorship).

**Comment by eocanha** [comment]
Pushed as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/ad3e51be9ed5271e2cababdb88a6d0cc67040bbd

**Comment by kkanag314** [comment]
Thank you @eocanha

**Pull request closed without merging**
