### PR TITLE
[GStreamer] fix assert isMainThread

### PR DESCRIPTION
**Pull request by tmaillart**

### CODE REVIEW

**Comment by philn** [comment]
Can you submit this upstream please? Some details in the commit message would be welcome too :)

**Comment by tmaillart** [comment]
Looks like it is fixed upstream https://github.com/WebKit/WebKit/commit/dadcac2683e98a375c206185919ad7f70ab7123e
My bad

**Comment by eocanha** [comment]
I'll try to have a look to this PR again to see if the upstream commit can somehow be backported to wpe-2.38.

**Comment by eocanha** [comment]
I think the solution merged upstream doesn't directly apply to the code design in wpe-2.38, because in upstream the current caps (as detected by the current thread) are passed as parameter of the lambda to be latter passed to a function, while in the current code the `updateConfigurationFromCaps()` and `updateConfigurationFromTags()` function take no parameter and just look up the right values when they are run on the main thread.

For that reason, I think that this PR makes sense for the current status of the code in the wpe-2.38 branch. I'm merging it but not proposing to port it upstream or to any other future branch.

**Pull request merged**
