### PR TITLE
Use the libWPE library from the upstream repository.

### PR DESCRIPTION
**Pull request by zdobersek**
Remove libWPE out of this source tree. libWPE from the upstream repository should be used. buildroot will be updated to build that package before bumping the wpe version.

### CODE REVIEW

**Comment by blino** [comment]
I have tried the staging-emev3 branch, and by default it does not run, I guess there is a similar issue with the change from this pull request:
  wpe: could not load the impl library. Is there any backend installed?: libWPE-backend.so: cannot open shared object file: No such file or directory

It can be run using:
  WPE_BACKEND_LIBRARY=/usr/lib/libWPE-platform.so

The WPE-platform library should probably be renamed.
And ideally extracted?

**Comment by zdobersek** [comment]
A fresh build works here.

libWPE.so is now built from a separate package, hard-coding libWPE-platform.so as the backend library name:
https://github.com/Metrological/buildroot-wpe/pull/25

**Comment by blino** [comment]
Ok, it needs to pass a specific -DWPE_BACKEND=libWPE-platform.so option during libWPE build.
Couldn't we just use the default backend library name?

**Comment by blino** [comment]
Could we do the same than in WPE-Mesa, adding a symlink?
https://github.com/WebKitForWayland/wpe-mesa/blob/master/CMakeLists.txt#L144

**Comment by zdobersek** [comment]
OK, switched to the symlink approach in https://github.com/Metrological/buildroot-wpe/commit/ee687de0338ce8d55667f336d807940193be9a46.

**Comment by blino** [comment]
I have created #233 to do the symlink directly from WPE-platform, so that it is common to all build systems, like WPE-mesa.

**Pull request merged**
