### PR TITLE
Clean-up media player on playback error

### PR DESCRIPTION
**Pull request by asurdej-comcast**

### CODE REVIEW

**Comment by eocanha** [comment]
Sorry, but I can't reproduce the issue that the "[HTMLMediaPlayer] Destroy media player on fatal playback error" commit tries to fix.

I've tried to use a corrupt webm/vp9 file, but the decoder won't cause a GST_FLOW_ERROR on corrupt data, as I intended. Then I used an encypted webm file without proper decryption setup (GStreamer complains about a missing plugin here) and that triggered a fatal playback error (appending happened just fine). After that fatal error, my test case tried first to attach a new MediaSource to the player, create a SourceBuffer and then append, but that's handled gracefully by an InvalidStateError on the SourceBuffer. Same if I don't create a new MediaSource and just reuse the old MediaSource and SourceBuffer from the failed attempt.

**Comment by calvaris** [comment]
This comes from https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/845 .

@asurdej-comcast As eocanha says, it would be nice to have a use case or at least some steps we can write into a test case for upstreaming.

**Comment by asurdej-comcast** [comment]
Hi, thanks for your feedbacks. There are two issues here in fact. The first one is solved by the backport (first commit - that seems reasonable in general) and the second one comes from VEVO app. There is and EOS triggered from MSE append pipeline (the reason for EOS is another topic) that reaches HTMLMediaElement as DecodeErr. This triggers detachMediaSource() while the player is still playing fine (it's not aware of any issue). Eventually the player reaches EOS when running out of samples and the playback is ended. The app tries to resume video with video.play() that triggers seek(0), ..., and finally MediaPlayerPrivateGStreamerMSE::sourceSetup that was trying to setPrivateAndOpen() on the MediaSource that was detached already and this was crashing. The crash itself was fixed by https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/880 that reopens MediaSource on loda() only but the player still keeps this detached MediaSource that may cause different issues. 

That's why I'm destroying the player to make sure it doesn't keep any state that is not valid any more and may cause crashes or further errors

**Comment by eocanha** [comment]
I've submitted https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/899/commits/692d0e2e076378b2b208ab0ba8c2e3073148392b upstream for review as https://github.com/WebKit/WebKit/pull/2122

**Comment by eocanha** [comment]
The changes landed upstream as https://github.com/WebKit/WebKit/commit/1c9cc6e485dc2ebd5604ba671a580ba5e7a9c7b7 and were backported downstream as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/9bb258ff9311d4ea7e55d3531f482d587cc591e4

Closing the PR.

**Comment by eocanha** [comment]
The upstream commit has caused a regression in some Mac tests. As the original crash was fixed in https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/880 / https://github.com/WebKit/WebKit/commit/45759ff and this commit is just preventive (the issue can't actually be reproduced upstream), I'm not going to insist about fixing the issue there.

Removing "upstream" tag.

**Comment by asurdej-comcast** [comment]
Hi @eocanha , thanks for your help here.
I saw upstream comment about crashes:
"This reverts because causing three imported/w3c/web-platform-tests/media-source/mediasource-changetype tests are a consistent crash."
Do you know if there is any place to find out more about failing/crahing TCs? (like Webkit CI or something). I will take a look, maybe I missed something.

As it was already backported to wpe-2.28 https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/9bb258ff9311d4ea7e55d3531f482d587cc591e4 should we also make a revert? (I would prefer keep the change)

**Comment by eocanha** [comment]
We can keep the commit downstream, no problem.

To find more about the crash, follow these steps:

1. Open https://results.webkit.org/ and filter for "platform: mac", "style: debug". Then look for these 3 tests in the search box one after another (they will accumulate as a list). You can also look for all the 5 mediasource-changetype tests, but these 3 are the only ones having regressions:
  - imported/w3c/web-platform-tests/media-source/mediasource-changetype-play.html
  - imported/w3c/web-platform-tests/media-source/mediasource-changetype-play-negative.html
  - imported/w3c/web-platform-tests/media-source/mediasource-changetype-play-without-codecs-parameter.html
2. Let's focus on mediasource-changetype-play.html by now. Scroll the timeline horizontally until the red failure (X) icons become purple crash (!) icons and then failure (!) ones again, around commits 253523@main ... 253621@main ... 253517@main. Note that the commit ids don't seem to be sequential sometimes, probably because there were gaps originally which were filled by later CI explicit retries. The one that seems to cause the problem is 253621@main (although it's actually the one fixing it, but appears here probably because in the process of landing that commit the bad and the good versions of the code might have gone trough CI).
3. Click on the first crash (!) there: "Big Sur E wk1 Debug on Macmini8,1 with x86_64" 253621@main and a bottom popup will appear. Click on [Test run](https://build.webkit.org/#/builders/3/builds/9115). That's the CI job that triggered the crash.
4. Open "17. extract-test-results", [View layout test results](https://build.webkit.org/results/Apple-BigSur-Debug-WK1-Tests/253522@main%20(9115)/results.html).
5. Open the [crash log](https://build.webkit.org/results/Apple-BigSur-Debug-WK1-Tests/253522@main%20(9115)/imported/w3c/web-platform-tests/media-source/mediasource-changetype-play-crash-log.txt) of mediasource-changetype-play.html. The relevant part there is on thread 0, frame 2: `WebCore::HTMLMediaElement::selectMediaResource()::$_0::operator()() const + 558 (HTMLMediaElement.cpp:1364)`. There must be a null pointer dereferencing, a failing assert or something like that there.
6. Let's see [the source code of the version with the offending patch applied](https://github.com/WebKit/WebKit/blob/1c9cc6e485dc2ebd5604ba671a580ba5e7a9c7b7/Source/WebCore/html/HTMLMediaElement.cpp#L1364). There's a failing assert there:
```
            //    Otherwise, if the media element has no assigned media provider object but has a src attribute, then let mode be attribute.
            mode = Attribute;
            ASSERT(m_player); <-- line 1364
            if (!m_player) {
                ERROR_LOG(logSiteIdentifier, "has srcAttr but m_player is not created");
                return;
            }
```

**Comment by asurdej-comcast** [comment]
Got it, thanks! I will try to fix it or rework original patch.
Thanks again for your support

**Pull request closed without merging**
