### PR TITLE
Wpe 2.22

### PR DESCRIPTION
**Pull request by Balajims88**
Hi @wouterlucas  
Have cherry-picked following changes from WebKit to fix build issue when enabling libwebrtc.
can you please merge this PR

https://github.com/WebKit/webkit/commit/2ba23ff3a127b1ee479481e5acceefed3eb6a601#diff-e15134acc0d8c2b7248c1160668ff725
https://github.com/WebKit/webkit/commit/5feb2aa7edf225f057ba99d81b10204dfdac4e97#diff-e15134acc0d8c2b7248c1160668ff725
https://github.com/WebKit/webkit/commit/9d678322281ccd07909759af90ee010e0c34b1c7#diff-e15134acc0d8c2b7248c1160668ff725
https://github.com/WebKit/webkit/commit/6f1447f2f76475ce8ec77116836c159a56760c48#diff-e15134acc0d8c2b7248c1160668ff725

### CODE REVIEW

**Comment by woutermeek** [comment]
@Balajims88 please resolve the merge conflicts. After you've done that we will validate the PR and merge if we don't see regression.

**Comment by Balajims88** [comment]
@woutermeek I have resolved the merge conflicts.
could you please validate the PR

**Comment by woutermeek** [comment]
Thanks @Balajims88 we will start a regression test cycle.

**Comment by Balajims88** [comment]
@woutermeek did you get a chance to looking into?

**Comment by woutermeek** [comment]
@Balajims88 yes, we are running regression tests on this build

**Comment by Balajims88** [comment]
Thanks @woutermeek for you merge.

**Pull request merged**
