### PR TITLE
RDK-38281: Fix WebAudio support on realtek platform

### PR DESCRIPTION
**Pull request by Scony**
This commit adds some custom settings for `GstRTKAudioSink` and excludes
some hardware decoders from participating in WebAudio processing.

This change is done on top of https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/961 and https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/966 - I'll remove that commits once pull requests go in

### CODE REVIEW

**Comment by eocanha** [comment]
In principle the patch looks good. Waiting for https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/966 question to Wouter/Ozgur to be clarified.

**Comment by eocanha** [comment]
@Scony, https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/966 has been merged. This PR can also be, as soon as you change it from Draft to active.

**Comment by Scony** [comment]
@eocanha that's good news. I've rebased this one and set as ready for review.

**Comment by eocanha** [comment]
Merging. Not upstreamable.

**Pull request merged**
