### PR TITLE
Bring back some useful SourceBuffer logs

### PR DESCRIPTION
**Pull request by Scony**

### CODE REVIEW

**Comment by eocanha** [comment]
@Scony, would these messages be still useful to you if they were declared as DEBUG_LOG()? I'd like to port this patch upstream and think that DEBUG_LOG() would pollute the logs a bit less for the general case. Do you agree?

**Comment by Scony** [comment]
@eocanha yes, that makes sense - should I update this PR or will you create upstream patch from scratch anyway?

**Comment by eocanha** [comment]
This PR is being tracked upstread in https://bugs.webkit.org/show_bug.cgi?id=247122 and https://github.com/WebKit/WebKit/pull/5854.

@Scony, I've already included the change to DEBUG_LOG() there, no need to update this PR.

**Comment by eocanha** [comment]
Upstream https://github.com/WebKit/WebKit/pull/5854 landed as https://github.com/WebKit/WebKit/commit/e5e73c6cc13de7853fde82bf4db544153af1eb7f and has been backported to wpe-2.28 as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/1850751afdf512a221a066e4bffa8439d8430a04 and https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/6bc889448cb16dc82914f3eb02d23bc1c2408273. Closing this PR.

**Comment by Scony** [comment]
thanks!

**Comment by eocanha** [comment]
Also, upstream https://github.com/WebKit/WebKit/pull/6044 landed as https://github.com/WebKit/WebKit/commit/445669890d9b15b6f2c452a7a03f2057c912ac8f and has been backported to wpe-2.28 as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/c564c9374bc34ddb493ab323ad049ee322c0d909

**Pull request closed without merging**
