### PR TITLE
Use SSLKEYLOGFILE env to enable logging SSL keys in libwebrtc / borin…

### PR DESCRIPTION
**Pull request by jacek-manko-red**
…gssl

For debugging, it's sometimes useful to be able to decrypt captured TLS traffic. By setting SSLKEYLOGFILE env variable, it's possible to log secrets to a file, which can then be used for decryption.
But libwebrtc uses a separate TLS implementation, boringssl, which does not support it by default.

Add key logging in libwebrtc if the env is set.

### CODE REVIEW

**Comment by modeveci** [comment]
Hi @philn , Can you look at this PR to see if it can be maintained? and please comment about coding style and IO api usage. Thank you very much!

**Comment by philn** [comment]
This is directly copy/pasted from https://boringssl.googlesource.com/boringssl/+/refs/heads/master/tool/client.cc so please give credit to the original author :)

**Comment by philn** [comment]
Have you tried mitmproxy?

**Comment by amol-virnodkar-infosys** [comment]
Hi @philn 
Since Jacek is not working in our team now, I have created a new PR: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1429 for this issue and we can continue the discussion in this PR. We can close the current PR: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1409.

**Pull request closed without merging**
