### PR TITLE
XMLHttpReques: allow disabling the cache for selected protocols

### PR DESCRIPTION
**Pull request by filipe-norte-red**
Cherry-pick commit 64c9073 from wpe-2.28

Note: Adjusted to fix build error

### CODE REVIEW

**Comment by magomez** [comment]
@filipe-norte-red seems that PR is ready for merge but it's still marked as WiP. Are you planning to do some more changes to it?

**Comment by filipe-norte-red** [comment]
@magomez , I'm waiting for an independent confirmation this is fixing the issue before making the pull request "official". Should receive it in the next days

**Comment by filipe-norte-red** [comment]
@magomez , I confirmed this is working as expected.

**Comment by filipe-norte-red** [comment]
For reference, attached index.html file allows testing this feature (with web inspector support)
[index.zip](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/13743144/index.zip)

**Pull request merged**
