### PR TITLE
Fix for faking readystate for livestreaming in PAUSED state.

### PR DESCRIPTION
**Pull request by kkanag314**

### CODE REVIEW

**Comment by eocanha** [comment]
It's a bit difficult to assess this patch as is. Please, can you give more context about the problem this patch is trying to solve, why that problem happens and why the patch is a solution for it? Thanks in advance.

**Comment by kkanag314** [comment]
For Live streaming the data will not be produced when the pipeline is in PAUSED state.The data will be generated once the pipeline transited to PLAYING state.
But in webkit,The Ready state is updated as Have_Enough_Data when the pipeline is in PAUSED state with NO_PREROLL(For Live streaming).
[ HAVE_ENOUGH_DATA - Enough data is available—and the download rate is high enough—that the media can be played through to the end without interruption.]Playing event will be triggered if the readystate has the value of Have_Future_Data/Have_Enough_Data.
For webrtc streaming,the faking of readystate in PAUSED state  leads to triggering a PLAYING event to application even before the connection has been established between the peers.
So We have done modification to update the Readystate as Have_Current_Data in PAUSED state for live streaming.

**Comment by eocanha** [comment]
This patch has no apparent regressions on regular live videos (tested with HLS, non-MSE player), so I've merged it.

**Comment by kkanag314** [comment]
Thanks @eocanha

**Pull request merged**
