### PR TITLE
Canvas glsync

### PR DESCRIPTION
**Pull request by asurdej-comcast**
Fix for https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/973

### CODE REVIEW

**Comment by magomez** [comment]
@asurdej-comcast , I'm waiting for feedback from Scony to commit the fix for https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/969, which will affect this PR (mainly the ImageBufferCairo part). After that patch is committed, I'd like you to give it a new test and check whether some problems may be already fixed (the point 1 that you mentioned should be already fixed).

Then, regarding the patch itself:
* In ImageBufferCairo, the call to glFinish instead of glFlush inside the #if PLATFORM(AMLOGIC) || PLATFORM(REALTEK) guard looks good. That's exactly what I was expecting.
* Don't remove the #if USE(GSTREAMER_GL) guards. Convert them into #if USE(GSTREAMER_GL) || (PLATFORM(AMLOGIC) || PLATFORM(REALTEK)) instead. Or add a new build option FORCE_BUFFER_SYNC (better FORCE_WEBGL_BUFFER_SYNC) and use it instead of #if PLATFORM(AMLOGIC) || PLATFORM(REALTEK). But we don't want to change the behavior for platforms that are not those.
* glFenceSync/glDeleteSync/glClientWaitSync are GLES3 functions. WPE is supposed to run with GLES2 and that's what it checks for. If you're 100% sure that GLES3 is always going to be available on the platforms where you're using them, and all the calls are properly protected by platform guards, I'm not against adding them as a fix for those platforms only. But if there are cases where they are not present, this will cause a build failure or a crash. In order to this properly, there should probably be a build check for GLES3, and disable FORCE_WEBGL_BUFFER_SYNC if GLES3 is not available.

**Comment by asurdej-comcast** [comment]
Hi @magomez, thanks for update. From what I know from Scony #969 patch fixes the https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/969 only (that canvas doesn't show up after video playback at all). My change is based on your patch (applied as the first "fix" commit), but my issues were still there. And both: 2d canvas cairo image and webgl were present. All in all lets wait for official feedback as it's pretty easy to get lost among different devices.

Regarding my changes we did some more testing with Amlogiic and Realtek devices and with my Amlogic it seem to work fine, but Realtek still has the same issues (expecially canvas 2d cairo image, blinking could be less visible but still - I don't have realtek device personally). 
And just to be clear the problem with 2d cairo image is that it ALWAYS draw "previous" state (not only the first draw). It's mostly visible at the first draw as usually it ends up with nothing/background.

E.g. for cairo image I was wondering about using single GL texture (m_compositorTexture) as it is modified from the main thread (swapBuffersIfNeeded) and read from compositor thread at the same time possibly that may lead to races especially with GL sync problems on the driver side. Do you think this may be an issue? Not sure if the same is applicable for webgl (NicosiaGC3DLayer) as it seems to swap between m_texture, m_compositorTexture and m_intermidate one.

Thanks

**Comment by magomez** [comment]
> Hi @magomez, thanks for update. From what I know from Scony #969 patch fixes the #969 only (that canvas doesn't show up after video playback at all). My change is based on your patch (applied as the first "fix" commit), but my issues were still there. And both: 2d canvas cairo image and webgl were present. All in all lets wait for official feedback as it's pretty easy to get lost among different devices.

#969 should fix both the problem after video playback and the problem of the first draw not being visible. That's going to be merged as soon as Scony can confirm that there are no regressions.

Your problems are indeed different, and I think that there's a problem in the video driver when doing GLES operations from different threads.

> Regarding my changes we did some more testing with Amlogiic and Realtek devices and with my Amlogic it seem to work fine, but Realtek still has the same issues (expecially canvas 2d cairo image, blinking could be less visible but still - I don't have realtek device personally). And just to be clear the problem with 2d cairo image is that it ALWAYS draw "previous" state (not only the first draw). It's mostly visible at the first draw as usually it ends up with nothing/background.
> 
> E.g. for cairo image I was wondering about using single GL texture (m_compositorTexture) as it is modified from the main thread (swapBuffersIfNeeded) and read from compositor thread at the same time possibly that may lead to races especially with GL sync problems on the driver side. Do you think this may be an issue? Not sure if the same is applicable for webgl (NicosiaGC3DLayer) as it seems to swap between m_texture, m_compositorTexture and m_intermidate one.

I think that the same problem is affecting both the canvas and webgl. In both cases some rendering operations are being performed on the main thread and the result is used from the compositor thread. It's important to notice that the access is not simultaneous: first the gl rendering operations on the main thread are performed, and after that a page repaint is requested and the compositor thread uses the rendering result to paint the page content.

In a functional driver (and I think your platforms are the only ones I've seen failing so far), the glFlush after the rendering on the main thread will send the gl commands to the video driver. Any other gl operation performed (by any thread) after that is guaranteed to be executed after the flushed commands. So when the compositor thread tries to get the rendered result, that access happens after the rendering commands have been issued, and the driver should guarantee that the read result is gotten after the rendering commands have been completed. I think this is the problem with the driver, that it's providing a result where not all the rendering commands have been executed, and hence the wrong results.
Things get better when using glFinish because glFinish blocks the main thread until all the gl operations are finished. Due to this, the page doesn't get repainted until all the gl operations are complete, guaranteeing that the result read in the compositor thread will get the content rendered after all the commands have been executed.

This would explain why the canvas shows the previous frame (the commands for the current frame haven't been processed yet), and the webgl blinking (we're switching among incomplete frames as well).

So, brief answer, I think the driver has a bug in how it's dealing with multithread gl operations. How to deal with this? The easiest solution is to replace glFlush with glFinish for those platforms, as you're doing with cairo. It has a performance penalty (block the main thread until the gl operations are done), but the result should be fine.

**Comment by magomez** [comment]
Something that's also weird is that you are able to use the glFenceSync/glDeleteSync/glClientWaitSync functions.

These functions are only available on GLES3. But, even if that's present in your platforms, WPE is always requesting a GLES2 context, so they shouldn't be available anyway, and you should get a build error or a crash using them. The only explanation that I can find that your driver has a GLES2 extension to implement this feature.

**Comment by asurdej-comcast** [comment]
@magomez Thanks, I will try playing with glfinish to see if it will fix the issue on realtek at all.

On GL versionn this is what glGetString(GL_VERSION); and glGetString(GL_EXTENSIONS); shows for my Amlogic:

`OpenGL ES 3.2 v1.r25p1-wayland-drm-g31-eabihf-rdk-805bd33d0-14.4dfffcf226055667dcb4fac60c780353`

`GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_astc_decode_mode GL_EXT_texture_compression_astc_decode_mode_rgb9e5 GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_buffer_storage GL_ARM_texture_unnormalized_coordinates
`

**Comment by asurdej-comcast** [comment]
This doesn't seem to entirely fix canvas issues, closing PR until better solution found

**Pull request closed without merging**
