### PR TITLE
[Fix] App freezes during Navigation If we inspect using RWI

### PR DESCRIPTION
**Pull request by kkanag314**
[Fix] App freezes during Navigation If we inspect using RWI

### CODE REVIEW

**Comment by kkanag314** [comment]
when app sends large message to their backend, network inspect agent sends the message to RWI which results in the busy loop blocking webkit main thread. Because it takes a while to read and transmit the message.

**Review by magomez — APPROVED** [review]

**Comment by blino** [comment]
@magomez @kkanag314 : this really helps performance with RWI, thanks for the patch!
Will this be submitted upstream?

**Comment by pgorszkowski-igalia** [comment]
@blino , @kkanag314 : I will try to upstream this change.

**Comment by pgorszkowski-igalia** [comment]
@blino , @kkanag314 : upstream PR: https://github.com/WebKit/WebKit/pull/39064

**Pull request merged**
