### PR TITLE
Add UI Client Callback for Console Log

### PR DESCRIPTION
**Pull request by vivekarumugam**
This has already been reviewed and merged into rdk-webrtc branch.

### CODE REVIEW

**Comment by igor-borovkov** [comment]
this can be frozen until this feature is really needed, the feature needs a review

**Comment by igor-borovkov** [comment]
this comment was for "intput element" events, not about console log

**Comment by vivekarumugam** [comment]
should we reopen the request or a new request without the "input focus" should be raised?

**Comment by igor-borovkov** [comment]
manual cherry pick would work better

**Comment by csaavedra** [comment]
I'm confused. What exactly needs review? I see the request is closed.

**Comment by vivekarumugam** [comment]
the pull request contains changes related to more than one features and one among them is still need to be discussed. So closing this and raising separate reviews for each change.

For the first commit, I have raised a new pull req : https://github.com/Metrological/WebKitForWayland/pull/96

**Comment by csaavedra** [comment]
Thanks.

**Comment by vivekarumugam** [comment]
No problem. I'll try to be clear next time :).

**Pull request closed without merging**
