### PR TITLE
Update gstreamer mediaplayers to use double instead of float

### PR DESCRIPTION
**Pull request by sarkanyi**
Some pages (live streams for example) can have time values which won't fit into float. I think it's time to update the gstreamer mediaplayers to use double as specified in the HTML5 specs.

I wonder if these changes if accepted could/should be pushed further upwards.
The changes shouldn't break anything.

### CODE REVIEW

**Review by zdobersek — APPROVED** [review]

**Comment by sarkanyi** [comment]
It seems I forgot that the pull request gets updated when I update my fork. The second commit is for fixing HLS. I wanted to make a second pull request for that, after the first one lands, but if it's ok for you, it can land with this also. It can be tested with: http://canalplus.github.io/rx-player/ - if you have no mouse use TAB and DOWN ARROW twice as the first stream doesn't seems to be accessible from outside of France.

**Comment by zdobersek** [comment]
MediaTime versions of methods inherited from MediaPlayerPrivateInterface are preferred. Those are being overridden in the wpe-staging branch that's being merged into master today.  Well, at least `durationMediaTime()` and `currentMediaTime()`. Others still need work.

So the first part of this PR will need updating. The HLS fix could go into a separate issue.

**Comment by sarkanyi** [comment]
@zdobersek I have reverted for now the HLS changes, now I need to wait for your updates then. I don't understand the problem with the currentTime etc. since in MediaPlayerPrivate.h the functions with the MediaTime versions are defined like this:
virtual MediaTime currentMediaTime() const { return MediaTime::createWithDouble(currentTimeDouble()); }

So overriding the currentTimeDouble() also fixes the MediaTime version.

**Comment by zdobersek** [comment]
@sarkanyi That's true. But implementing currentMediaTime() instead of currentTimeDouble() is preferable because float and double versions of these methods should be removed in the future.

**Comment by sarkanyi** [comment]
@zdobersek: ok, the change for this is pretty easy. I will have to test it though

**Comment by sarkanyi** [comment]
Not sure if merging was a brilliant idea from my side, but rebasing would've caused the pull request to close.

**Pull request closed without merging**
