### PR TITLE
Fixing memory leak for Westeros backend

### PR DESCRIPTION
**Pull request by vertexodessa**

### CODE REVIEW

**Comment by philn** [comment]
Next time please submit changes for the master branch.

**Comment by igor-borovkov** [comment]
Hi Philippe, we use comcast-master for our daily QA builds, could you and other Metrological devs not push changes to this branch please.  @kraj

**Comment by philn** [comment]
Then no need for pull-requests, just push directly to that branch?

**Comment by igor-borovkov** [comment]
hi,
traditionally all our builds used our own hosted git repos. for the purpose of simplified upstreaming Khem wants to use github, and for even faster/simpler upstreaming Khem wanted to use your repo. We can't just pull master branch into our builds, so we created comcast-master...  traditionally we also have code reviews for every commit, thus no direct pushing... I think it's better if Azam, Eugene, Ihor would create pull request directly to your "master" then we'll pull to comcast-master

**Comment by philn** [comment]
Why can't you pull master into your builds?

**Pull request merged**
