### PR TITLE
[wpe-2.38][MSE] Synchronize video seeking events

### PR DESCRIPTION
**Pull request by asurdej-comcast**
HTMLMediaElement sends 'seeking' and 'seeked' events from separate event queue that is not in sync with player callbacks. Seeking MSE video into buffered range may complete the seek (by m_player->timeChanged()) faster then 'seeking' event is dispatched to JavaScript. They both runs on the same main thread but different queues. As a result JavaScript is not able to notice video.seeking property (as it is 'false' again when 'seeking' event reaches JavaScript).

The solution is taken from audio-only streams https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1232
and extended for video also. It puts timeChanged() notification on HTMLMediaElement event queue, the same that keeps JavaScript events to make sure everything is in sync.

This works around and issue from https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1347

PS. I think https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1211 is not needed any more because of https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1338  and current didPreroll() implementation. But I don't have initial test case to confirm.

### CODE REVIEW

**Comment by calvaris** [comment]
Is this a fix for #1347 ?

**Comment by asurdej-comcast** [comment]
Yes, it is, but I'm not fully sure if it is enough. Currently seeking can be finished from timeChanged() and readyStateChanged() notifications. This will fix timeChanged flow when readyState doesn't change (MSE data buffered).
In case of readyState change, it requires mse data append from JS that takes some time and the issue is not visible

**Comment by calvaris** [comment]
Well, this does not work as fix for #1347, at least on the rpi. I am closing this and we can continue in the issue.

**Comment by asurdej-comcast** [comment]
@calvaris omg TC hit the second flow that finishes seek from readyStateChange() . See my previous comment.
The reason is that I append only one data segment and readyState is flipping between EnoughData and FutureData depending on currentTime. Appending one more segment fixes this flow and TC works fine with this PR. Anyway, the fix here is not enough

**Comment by calvaris** [comment]
Let's continue at #1347 , please.

**Pull request closed without merging**
