### PR TITLE
[AMLOGIC] Fix for wait for audio & disable xrun timer

### PR DESCRIPTION
**Pull request by mbhatt627**
1-  When the audio data reaches the amlhalasink later than  0.7s a xrun timer is triggered
 and it is moved to the paused state also  causing a video freeze. Disable the
 xrun timer, so that video wont freeze when in slow network
2- enables 'wait-video' in aml audio sink

### CODE REVIEW

**Comment by eocanha** [comment]
Is there any relevant define that you can check, so the code can be wrapped in #if / #endif blocks like the Broadcom code is?

**Comment by mbhatt627** [comment]
> Is there any relevant define that you can check, so the code can be wrapped in #if / #endif blocks like the Broadcom code is?

amlhalsink is the Amlogic GST element , So it wil work only on Amlogic.

**Comment by woutermeek** [comment]
Indeed @mbhatt627, there is no need to run this code on any other platform. So it would be a bit wasteful to have this code on non amlogic devices. Therefor it would be better to encapsulate it in an ifdef. Could you please add an ifdef to it?

**Comment by mbhatt627** [comment]
Added AMLOGIC_PLATFORM define , @woutermeek , @eocanha .

**Comment by eocanha** [comment]
Thanks for the update, @mbhatt627.

The branch as it was today wasn't applying cleanly on top of wpe-2.28, so I fixed the conflicts locally and manually pushed the commit to wpe-2.28 as https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/a1044709ab29804bc21624611dfd992b12bdd39b

This commit is too platform-specific and doesn't make sense to port it upstream.

Closing the PR.

**Comment by eocanha** [comment]
Sorry for the missign "{" in this commit I finally pushed, which had to be fixed on https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/893 😇

**Pull request closed without merging**
