### PR TITLE
Enable network process side buffering

### PR DESCRIPTION
**Pull request by emutavchi**
Reduce IPC overhead on loading some types of resources.

### CODE REVIEW

**Comment by zdobersek** [comment]
Any subtle break possible due to using ENABLE(NETWORK_CACHE) code path when otherwise ENABLE(NETWORK_CACHE) is disabled?

**Comment by emutavchi** [comment]
Hi @zdobersek , all I found is that it was disabled because of regression in Minibrowser for EFL port: https://bugs.webkit.org/show_bug.cgi?id=137692 . I couldn't reproduce that issue.

**Comment by carlosgcampos** [comment]
I don't see any reason why buffering should be broken with disk cache disabled. This looks like a real bug in the past that EFL worked around that way. EFL is gone now, so it's time to simply remove that check from upstream instead of adding more ifdefs.

**Comment by carlosgcampos** [comment]
https://bugs.webkit.org/show_bug.cgi?id=168637

**Comment by carlosgcampos** [comment]
Patch landed upstream http://trac.webkit.org/changeset/212816

**Comment by zdobersek** [comment]
Let's merge this as is, it can be aligned with upstream later.

**Pull request merged**
