### PR TITLE
More build fixes for gcc 4.8

### PR DESCRIPTION
**Pull request by blino**
This adds more build fixes for gcc 4.8, on top of the gcc48 branch.
It builds and runs successfully with the bcm-nexus backend.

### CODE REVIEW

**Comment by zdobersek** [comment]
LGTM.

**Comment by blino** [comment]
Not sure if you noticed, this was a merge request towards the gcc48 branch.
Maybe we need more peer reviewing (Guillaume?) before merging in master.

**Comment by zdobersek** [comment]
Noticed it. I am against supporting GCC 4.8 in master.

**Comment by zdobersek** [comment]
Even if the check in Source/WTF/wtf/Compiler.h was changed to seemingly support it. What's problematic now is that large changesets have to be reverted to keep things compiling.

**Comment by blino** [comment]
Yes, these large reverts will be a problem in the long run, and even just now with the latest upstream merge in master.
@wouterlucas think this is manageable for a few months, I am not so sure.

**Comment by wouterlucas** [comment]
At some point investing into this will outweigh the benefits of having a latest and greatest WPE on systems that have a SoC provided GCC 4.8 toolchain. Eventually we'll just have to leave it at a branch somewhere. But for now we will have to bridge this a little longer so we can give people the opportunity to move away from GCC4.8. The faster that happens the better for all.

**Comment by kraj** [comment]
We are already testing gcc 4.9 and we might be able to lift this restrictions provided everything works out well.

**Comment by wouterlucas** [comment]
@kraj I think @blino is limited by a BCM provided 4.8 toolchain. Getting BCM to move that will take longer. I guess it's never to late to move to OE/BR @blino =)

**Comment by zdobersek** [comment]
I can reduce pulls from upstream to a monthly occurrence. That would make the whole codebase a bit more stable to work with in general, and the 4.8 compat effort would only require one iteration per month (though at this point there would be a lot more reverts needed I think).

What I need is a guarantee that in the near future (6 months maximum, anything less would be much more appreciated) we can drop 4.8 compatibility and undo the reverts. With that I can live with these fixes in master.

**Comment by blino** [comment]
@wouterlucas I also have a crosstool-ng toolchain with gcc > 4.8, this can be fine for development, but this is an issue for deployments where we will get limited support from the chipset vendor if we do not use the supplied toolchain.

**Pull request merged**
