### PR TITLE
GSTMediaPlayer: Fix typos

### PR DESCRIPTION
**Pull request by asurdej-comcast**
Fix refactoring typos "var != nullptr" -> "!var"

### CODE REVIEW

**Comment by philn** [comment]
cc @calvaris I guess this is going to need upstreaming too?

**Comment by calvaris** [comment]
Sure it does. @asurdej-comcast can you report this upstream, please?

**Comment by asurdej-comcast** [comment]
@calvaris @philn Created upstream bug and PR:
https://bugs.webkit.org/show_bug.cgi?id=256083
https://github.com/WebKit/WebKit/pull/13266

**Comment by calvaris** [comment]
Landed downstream as d4e6d371d0d9b5b4c71cfe1f68676ba198cbc5bf .

**Pull request closed without merging**
