### PR TITLE
Gamepad Platform implementation for WPE

### PR DESCRIPTION
**Pull request by Haseenamol**
Gamepad platform implementation added to WPE. 
Tested using W3C gamepad testcases: 
Details updated in https://metrological.atlassian.net/browse/WPE-45

### CODE REVIEW

**Comment by zdobersek** [comment]
New source files need license headers.

Not sure whether:
1. this should use udev to scrap together joystick devices
2. there could be WK2 API that would basically allow the user to implement what GamepadProviderWPE does.

**Comment by Haseenamol** [comment]
Thank you Zan for your comments.
1. The joystick add/remove detected we have implemented based on udev rule.
For working this gamepad functionality, we have to enable CONFIG_INPUT_JOYSTICK in linux kernel + add udev rule in the RFS.
2.  WK2 APIs: Agreed

**Comment by zdobersek** [comment]
Re: 1, I was having the libudev library in mind. It does add another dependency though.

**Comment by Haseenamol** [comment]
1. Is the current implementation using "CONFIG_INPUT_JOYDEV" + "CONFIG_INPUT_JOYSTICK" in the kernel fine ? Do we need to use libudev lib ? Please confirm

**Comment by zdobersek** [comment]
Yeah, it's fine. We can try the udev library later.

**Comment by zdobersek** [comment]
This will need some modification after today's merge of wpe-staging into master. The basics stay the same, but the code should be moved under Source/WebKit2/UIProcess/Gamepad/, and adjusted to the new interfaces.

Please do that, I'll put more attention to it and have it reviewed soon.

**Pull request closed without merging**
