### PR TITLE
Add provision to enable / disable websecurity

### PR DESCRIPTION
**Pull request by varumugam123**

### CODE REVIEW

**Comment by varumugam123** [comment]
Wondering if the AllowRunningOfInsecureContent & AllowDisplayOfInsecureContent should also be exposed

**Comment by varumugam123** [comment]
Added AllowRunningOfInsecureContent & AllowDisplayOfInsecureContent preferences as in wpe-2.22 also added properties & apis corresponding to it

**Comment by magomez** [comment]
I understand the webSecurity setting (despite it should be used for testing only), but I don't get why AllowRunningOfInsecureContent and AllowDisplayOfInsecureContent are needed. Specially with this implementation that just adds the the settings but doesn't do anything with them.

@varumugam123, why do you need those settings?

**Comment by varumugam123** [comment]
Hi @magomez , AllowDisplayOfInsecureContent  & AllowRunningOfInsecureContent  are already part of Settings and used by MixedContentChecker, just that they are not exposed outside as preferences.

https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.28/Source/WebCore/page/Settings.yaml#L284
https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.28/Source/WebCore/loader/MixedContentChecker.cpp#L77
https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.28/Source/WebCore/loader/MixedContentChecker.cpp#L96

These are required by few apps like Amazon

**Comment by magomez** [comment]
I think you're mixing WebPreferences and Settings. WebPreferences is the class used to pass configuration values to the engine, which in the glib API is wrapped inside a WebKitSettings class. This is where the WebSecurityEnabled parameter is, and where you added AllowRunningOfInsecureContent and AllowDisplayOfInsecureContent. So those values are configurable from the app through the API you added, fine.

Settings is an internal class that holds configuration parameters. This class already contains the WebSecurityEnabled, AllowRunningOfInsecureContent and AllowDisplayOfInsecureContent parameters. Some of those parameters might be configurable from the app, and in order to that you need to create a new entry inside WebPreferences, and then propagate the value from this new WebPreferences entry into the Settings class. MixedContentChecked is using the AllowRunningOfInsecureContent and AllowDisplayOfInsecureContent values from this class (Settings, not WebSettings).

So with this PR you now have API to set/get WebSecurityEnabled, AllowRunningOfInsecureContent and AllowDisplayOfInsecureContent on WebPreferences, but those values are not being propagated to the internal Settings class, so they will be never used by MixedContentChecker, for example. That's why I said that this implementation just adds the settings but doesn't do anything with them. You're missing a piece here, that propagates the WebPreferences values into the Setttings. This is usually done inside WebPage::updatePreferences(). You'll see a lot of other properties being propagated there.

**Comment by magomez** [comment]
I didn't realize that the settings were already being update through WebPage::updatePreferencesGenerated, they are already being propagated properly.

**Pull request merged**
