### PR TITLE
[WPE-511][MSE] Update |m_playbackRatePause| also in MSE path.

### PR DESCRIPTION
**Pull request by pawel-stanek-ml**
Otherwise in MSE case the following calls do not make playback to
start as expected:

mediaElement.setRate(0);
mediaElement.play();
mediaElement.setRate(1);

### CODE REVIEW

**Review by eocanha — COMMENTED** [review]
In the "rate 0, play, rate 1" example you mention in the log text, can you explain a bit how the mechanism to continue playback would work?

On the one hand, [MediaPlayerPrivateGStreamer::play()](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp#L480) would automatically set m_playbackRatePause to true when rate==0, so [m_playbackRatePause = !m_playbackRate](https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/644/commits/dbd417f3dfd952da571893583f845728352e248b#diff-52262bbefc8558f6ad277f98a4f6ebbeR409) wouldn't apparently be needed in the scenario you present. On the other hand, [MediaPlayerPrivateGStreamerMSE::doSeek()](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp#L401) will perform a seek with the new rate 1, but [MediaPlayerPrivateGStreamerMSE::updatePlaybackRate()](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp#L450) does nothing on MSE, unlike its regular player counterpart, which is in charge of restoring the pipeline state to GST_STATE_PLAYING [here](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp#L681).

**Comment by pawel-stanek-ml** [comment]
You're absolutely right. These calls do not show the full picture.
Due to the fact play() is  called when the rate is 0 the pipeline is not set to PLAYING but the "rate paused" flag is set instead. The key issue with it is it's never really cleared in MSE unless pause() is called (due to mentioned updatePlaybackRate() doing nothing in MSE). Moreover the flag is special cased in paused()  which returns false when the flag is set. This later causes play() to never be called again automatically (which it normally is by updatePlayState() for shouldBePlaying and playerPaused - but playerPaused is false because of the flag as mentioned earlier). This is why flag clearance is a must IMO - and enough for my case. However now when thinking about it, I think that apart from flag clearance a code should be added to move pipeline to PLAYING state (and possibly moved to ...MSE::updatePlaybackRate() too).

**Comment by pawel-stanek-ml** [comment]
Now we have MSE and non MSE aligned in this matter - and I guess this is something you suggested, kind of.

**Review by eocanha — APPROVED** [review]
I wasn't very sure about what would happen with the new updatePlaybackRate() code with a sequence of actions like "rate 0, play, pause, rate 1, play", but I wrote a quick html example here locally and the new code behaves properly. The patch looks good to me as it's now.

**Pull request merged**
