### PR TITLE
Revert the scheduleNotifyAboutPlaying() changes

### PR DESCRIPTION
**Pull request by varumugam123**
This is a cherry pick of 87cbd6c from wpe-2.22 to wpe-2.28 for https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/816

### CODE REVIEW

**Comment by eocanha** [comment]
I've ported this patch locally to upstream WebKit, checked that there are no apparent regressions, and worked on writing a layout test that mimicks the seeking.html example from https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/700, but I'm not there yet.

**Comment by varumugam123** [comment]
Hi @eocanha , Actually the above change is part of a fix. As I mentioned #821 & #816 are kind of related.

In one case (#821) playing event is sent from wpe-2.28 when it is not expected (firefox & chrome don't send that event)... In #816, during seeking buffered range, the playing event is not sent (firefox & chrome browsers send the event).

Please refer output from firefox (left one) & chrome browsers with the sample page which seeks within buffered range (https://github.com/WebPlatformForEmbedded/WPEWebKit/files/6070937/seeking.html.txt)

image

In wpe-2.28 the "playing" event is missing.
```
root@hisense-a6gp:/opt# grep dispatchEvent /opt/logs/wpeframework.log  | grep VIDEO | grep -v timeupdate
2022 Apr 01 13:23:23.921408 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent loadstart on node VIDEO
2022 Apr 01 13:23:23.954244 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent play on node VIDEO
2022 Apr 01 13:23:23.954669 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent waiting on node VIDEO
2022 Apr 01 13:23:24.588116 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent durationchange on node VIDEO
2022 Apr 01 13:23:24.590238 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent durationchange on node VIDEO
2022 Apr 01 13:23:24.591412 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent resize on node VIDEO
2022 Apr 01 13:23:24.591962 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent loadedmetadata on node VIDEO
2022 Apr 01 13:23:24.647170 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent loadeddata on node VIDEO
2022 Apr 01 13:23:24.651566 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent canplay on node VIDEO
2022 Apr 01 13:23:24.653336 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent playing on node VIDEO
2022 Apr 01 13:23:24.733424 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent canplaythrough on node VIDEO
2022 Apr 01 13:23:26.790755 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent durationchange on node VIDEO
2022 Apr 01 13:23:27.893160 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent stalled on node VIDEO
2022 Apr 01 13:23:28.744411 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent seeking on node VIDEO
2022 Apr 01 13:23:28.956902 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent waiting on node VIDEO
2022 Apr 01 13:23:28.957799 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent seeked on node VIDEO
2022 Apr 01 13:23:28.958167 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent canplaythrough on node VIDEO
2022 Apr 01 13:23:28.959034 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent canplay on node VIDEO
2022 Apr 01 13:23:28.960319 WPEFramework[13583]:  [WPEWebKit:Events:4] EventDispatcher::dispatchEvent canplaythrough on node VIDEO
```

**Comment by eocanha** [comment]
I've completed the layout test locally (attached) and realized that upstream actually sends the waiting and playing events when seeking to an unbuffered area, so the patch isn't needed upstream.
Because of this, I'm going to approve the patch on 2.28, with the peace of mind that porting it to a future wpe version won't be needed. That's why I'm also removing the "upstream" tag from this PR.

**Comment by eocanha** [comment]
[LayoutTests_media_media-source_media-source-video-playing-after-seek.html.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8398702/LayoutTests_media_media-source_media-source-video-playing-after-seek.html.txt)

This test is experimental (too many currentTime log lines that can't fit on an expectations file), but serves to prove that waiting/playing events are actually emitted upstream when seeking to an unbuffered range that will be filled later.

**Comment by eocanha** [comment]
Note that the waiting/playing events will *only* be emitted if the seek target time is unbuffered. If it's buffered (eg: because the machines is powerful and has processed the appends very quickly), nothing will actually prevent a smooth video playback, and therefore the waiting/playing events won't be emitted.

I noticed this while running your test case upstream: the appends completed so quickly in my computer that the area was actually buffered when seek was called. I had to add a setTimeout() after the updates of each append to force a delay in the next append and actually have unbuffered areas when seek was called.

**Comment by eocanha** [comment]
My understanding is that this PR fixes issue #816.

**Pull request merged**
