### PR TITLE
Encrypted hevc support

### PR DESCRIPTION
**Pull request by pawel-stanek-ml**
With CENC encryption.

### CODE REVIEW

**Comment by calvaris** [comment]
Adding this to my to-do.

**Comment by pawel-stanek-ml** [comment]
Any updates here?

**Comment by calvaris** [comment]
> Any updates here?

No, my to-do keeps growing.

**Comment by calvaris** [comment]
But fear not, I didn't forget it. Just there are higher priority tasks on my plate.

**Comment by pawel-stanek-ml** [comment]
> But fear not, I didn't forget it. Just there are higher priority tasks on my plate.

:+1:

Please note this one is tiny unless I'm missing something.

**Comment by calvaris** [comment]
Tiny means I have to port it upstream, get it reviewed and port it back down. Tiny is relative.

**Comment by 404ag** [comment]
Hi @calvaris, any update on this PR?

**Comment by calvaris** [comment]
> Hi @calvaris, any update on this PR?

No, sorry, still swamped with other tasks.

**Comment by 404ag** [comment]
Do you know when it is going to be picked up and finished?

**Comment by calvaris** [comment]
> Do you know when it is going to be picked up and finished?

This is in my to-do list, definitely, but I can't tell you because I don't know when I'll finish my current task and the other ones before this.

**Review by calvaris — APPROVED** [review]

**Pull request merged**
